### ISSUE TITLE
Server suddenly stops working

### ISSUE THREAD

**Issue by MoraesCaio** [gpassero/cogroo4py#2]
Hi, after few hours the server does not respond (maybe it's on loop) when i try to lemmatize. I've tested the last input after restarting the server and it works fine so t's not a problem related to the input I'm using python 3.6, open-jdk-8.
Also, the number of the server child processes have increased since the beginning:
https://imgur.com/a/IityAyR

**Comment by gpassero** [comment]
Hi Caio, have you experienced the issue consistently? If so, what's the usual time the server takes to crash? Also, could you share part of your code so I can more easily reproduce the issue here?

**Comment by MoraesCaio** [comment]
```python
cogroo_path = path.join('cogroo4py', 'cogroo4py.jar')
command = ['java', '-jar', path.join(current_dir, cogroo_path)]
process = Popen(command, stdout=PIPE, stdin=PIPE) # i've also tried using bufsize=0 for Popen constructor

word_lemma = cogroo.lemmatize(word)
```

**Comment by MoraesCaio** [comment]
This error is always happening in the span of 1 day. Sometimes it takes around 18 hours, sometimes 5-6 hours.

**Comment by gpassero** [comment]
I see. Since it's hard to reproduce, I'll try recompiling `cogroo4py.jar` for a more recent version of Java (it currently only works with Java 8) and check if that improves performance and reduces the use of computational resources. If the problem persists there, I'll try to reproduce it to debug it.

Also, the log you posted suggests you are running `cogroo4py.jar` too many times. You just need to run it once, it will open a socket to interact with the JVM with CoGrOO loaded there. Could you confirm how many times you are running `cogroo4py.jar`?

**Comment by MoraesCaio** [comment]
Hi. This is not the case, because i only instantiate the server if there's no server running before. Those are subprocesses created by cogroo4py.jar (i've used the tree-style exhibition (F5 shortcut) of htop in the screenshot). Also, trying to run it twice will raise an exception due to the address already being binded.
To check if the server is up i use the following code. find_server_proc() always return a one-element list unless i try to run another server instance manually. 
```python
import psutil
from subprocess import Popen, PIPE

def find_server_proc():
    "Return a list of server processes."
    ls = []
    for p in psutil.process_iter(attrs=["cmdline"]):
        if p.info["cmdline"] and\
            len(p.info["cmdline"]) > 2 and\
                "cogroo4py.jar" in p.info["cmdline"][2]:
            ls.append(p)
    return ls

def instantiate_server():
    if not find_server_proc():
        cogroo_path = path.join("cogroo4py", "cogroo4py.jar")
        command = ["java", "-jar", path.join(current_dir, cogroo_path)]

        process = Popen(command, stdout=PIPE, stdin=PIPE, bufsize=0)

        while True:
            # Waiting for the server to be ready
            if "gateway server started" in output.decode().lower() or \
                    process.poll() is not None:
                break

            time.sleep(0.1)
```

**Comment by gpassero** [comment]
@MoraesCaio I could reproduce your issue by running:

```python
from cogroo_interface import Cogroo

instantiate_server()
for i in range(1000):
  print(Cogroo.Instance().lemmatize("Hey " + str(i))) # freezes at request ~100
```

I noticed the problem doesn't happen if I start the Java server from outside python (from OS terminal), so I think the problem is related to the use or misuse of the `subprocess` library. I don't know this library in deep and I still could not find the reason it happens. 

Could you please try to start your Java server from your OS terminal instead of from python? If the issue still happens, please try out the new Java server version I've just released today for Java 12 and let me know how it goes. This may fix your issue because of the lot of optimizations applied to the Java compiler since version 8 (which was the only one available for cogroo4py before this release).

**Comment by gpassero** [comment]
Hi @MoraesCaio. Long time no see, huh? 😄 

I'd be happy to know if you had any progress with this problem. Please let me know if you have any updates. 😉

**Comment by MoraesCaio** [comment]
Hey, sorry for the late answer,
So, i was working with docker/kubernetes and found that there is a known memory leak with it while running server-like systems inside of it. The same thing also happens with Tensorboard (google's logger for machine learning).
In the end, one of my co-workers solved the issue by replacing py4j by pyjnius which does not require that server-like communication between python and java. We kept using java 8, so i don't think that's the cause of the bug.

**Comment by gpassero** [comment]
Interesting! Do you see any other advantage in using pyjnius? Please feel free to open a PR with your fix if you think that could lead to a more stable version of cogroo4py. Otherwise, I don't see anything else we could do based on what we've discussed. 🤷
